import {act,cleanup,renderHook} from '@testing-library/react'
import {afterEach,describe,expect,it,vi} from 'vitest'
import {api,ApiError} from './api'
import {beginDraft,editDraft,type Note} from './state'
import {useNoteDrafts} from './useNoteDrafts'

const note=(id:string,body:string,version=1):Note=>({id,title:id,body,project_id:'',version,created_at:'2026-01-01T00:00:00Z',updated_at:'2026-01-01T00:00:00Z'})
const deferred=<T,>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes});return {promise,resolve}}
const tick=async(ms=1000)=>{await act(async()=>{await vi.advanceTimersByTimeAsync(ms)})}
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.useRealTimers()})

describe('useNoteDrafts autosave',()=>{
 it('keeps a confirmed PATCH saved when refresh rejects and does not resend it',async()=>{
  vi.useFakeTimers()
  const update=vi.spyOn(api,'update').mockResolvedValue({item:note('A','local',2)})
  const reload=vi.fn().mockRejectedValue(new Error('refresh failed'))
  const {result}=renderHook(()=>useNoteDrafts(reload,vi.fn(),true))
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','old')),{body:'local'})))
  await tick()
  expect(result.current.drafts.A).toMatchObject({body:'local',version:2,status:'saved'})
  expect(result.current.drafts.A.errorMessage).toContain('The note was saved, but the list could not be refreshed')
  await act(async()=>result.current.save(result.current.drafts.A))
  expect(update).toHaveBeenCalledTimes(1)
 })
 it('saves the newest edit after PATCH succeeds and refresh rejects while its timer was blocked',async()=>{
  vi.useFakeTimers()
  let rejectReload!:(reason:Error)=>void
  const reload=new Promise<void>((_resolve,reject)=>{rejectReload=reject})
  const update=vi.spyOn(api,'update').mockResolvedValueOnce({item:note('A','first',2)}).mockResolvedValueOnce({item:note('A','latest',3)})
  const {result}=renderHook(()=>useNoteDrafts(()=>reload,vi.fn(),true))
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','old')),{body:'first'})))
  await tick()
  act(()=>result.current.setDraft(editDraft(result.current.drafts.A,{body:'latest'})))
  await tick()
  expect(update).toHaveBeenCalledTimes(1)
  await act(async()=>rejectReload(Error('refresh failed')))
  await tick(0)
  expect(update).toHaveBeenNthCalledWith(2,'notes','A',{title:'A',body:'latest',project_id:'',version:2})
  expect(result.current.drafts.A).toMatchObject({body:'latest',version:3,status:'saved'})
 })
 it('keeps an overlong UTF-8 title editable, blocks PATCH and saves after correction',async()=>{
  vi.useFakeTimers()
  const update=vi.spyOn(api,'update').mockResolvedValue({item:note('A','body',2)})
  const {result}=renderHook(()=>useNoteDrafts(async()=>{},vi.fn(),true))
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','body')),{title:'á'.repeat(121)})))
  await tick()
  expect(update).not.toHaveBeenCalled()
  expect(result.current.drafts.A).toMatchObject({status:'error',title:'á'.repeat(121)})
  expect(result.current.drafts.A.errorMessage).toMatch(/242 bytes UTF-8/)
  act(()=>result.current.setDraft(editDraft(result.current.drafts.A,{title:'á'.repeat(120)})))
  await tick()
  expect(update).toHaveBeenCalledWith('notes','A',expect.objectContaining({title:'á'.repeat(120)}))
 })
 it('saves the newest edit after its timer fires during an outstanding PATCH',async()=>{
  vi.useFakeTimers()
  const first=deferred<{item:Note}>(),second=deferred<{item:Note}>()
  const update=vi.spyOn(api,'update').mockImplementationOnce(()=>first.promise).mockImplementationOnce(()=>second.promise)
  const reload=vi.fn(async()=>{})
  const {result}=renderHook(()=>useNoteDrafts(reload,vi.fn(),true))
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','server')),{body:'first'})))
  await tick()
  expect(update).toHaveBeenNthCalledWith(1,'notes','A',{title:'A',body:'first',project_id:'',version:1})
  act(()=>result.current.setDraft(editDraft(result.current.drafts.A,{body:'latest'})))
  await tick()
  expect(update).toHaveBeenCalledTimes(1)
  await act(async()=>{first.resolve({item:note('A','first',2)});await first.promise})
  await tick(0)
  expect(update).toHaveBeenNthCalledWith(2,'notes','A',{title:'A',body:'latest',project_id:'',version:2})
  await act(async()=>{second.resolve({item:note('A','latest',3)});await second.promise})
  expect(result.current.drafts.A).toMatchObject({body:'latest',version:3,status:'saved'})
  expect(reload).toHaveBeenCalledTimes(2)
 })
 it('saves the newest edit when its timer fires during reload after PATCH succeeds',async()=>{
  vi.useFakeTimers()
  const pendingReload=deferred<void>(),second=deferred<{item:Note}>()
  const update=vi.spyOn(api,'update').mockResolvedValueOnce({item:note('A','first',2)}).mockImplementationOnce(()=>second.promise)
  const reload=vi.fn().mockImplementationOnce(()=>pendingReload.promise).mockResolvedValue(undefined)
  const {result}=renderHook(()=>useNoteDrafts(reload,vi.fn(),true))
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','server')),{body:'first'})))
  await tick()
  expect(reload).toHaveBeenCalledTimes(1)
  act(()=>result.current.setDraft(editDraft(result.current.drafts.A,{body:'latest'})))
  await tick()
  expect(update).toHaveBeenCalledTimes(1)
  await act(async()=>{pendingReload.resolve();await pendingReload.promise})
  await tick(0)
  expect(update).toHaveBeenNthCalledWith(2,'notes','A',{title:'A',body:'latest',project_id:'',version:2})
  await act(async()=>{second.resolve({item:note('A','latest',3)});await second.promise})
  expect(result.current.drafts.A).toMatchObject({body:'latest',version:3,status:'saved'})
 })
 it('saves an edit whose timer fires after PATCH and reload have finished',async()=>{
  vi.useFakeTimers()
  const first=deferred<{item:Note}>()
  const update=vi.spyOn(api,'update').mockImplementationOnce(()=>first.promise).mockResolvedValueOnce({item:note('A','latest',3)})
  const {result}=renderHook(()=>useNoteDrafts(async()=>{},vi.fn(),true))
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','server')),{body:'first'})))
  await tick()
  act(()=>result.current.setDraft(editDraft(result.current.drafts.A,{body:'latest'})))
  await act(async()=>{first.resolve({item:note('A','first',2)});await first.promise})
  await tick()
  expect(update).toHaveBeenNthCalledWith(2,'notes','A',{title:'A',body:'latest',project_id:'',version:2})
  expect(result.current.drafts.A).toMatchObject({body:'latest',version:3,status:'saved'})
 })
 it('keeps other notes independent while one PATCH is pending',async()=>{
  vi.useFakeTimers()
  const pending=deferred<{item:Note}>()
  const update=vi.spyOn(api,'update').mockImplementation((_name,id)=>id==='A'?pending.promise:Promise.resolve({item:note('B','new B',8)}))
  const {result}=renderHook(()=>useNoteDrafts(async()=>{},vi.fn(),true))
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','old A')),{body:'new A'})))
  await tick()
  act(()=>result.current.setDraft(editDraft(beginDraft(note('B','old B',7)),{body:'new B'})))
  await tick()
  expect(update).toHaveBeenCalledTimes(2)
  expect(result.current.drafts.B).toMatchObject({body:'new B',version:8,status:'saved'})
  await act(async()=>{pending.resolve({item:note('A','new A',2)});await pending.promise})
 })
 it('does not retry a real conflict or failed PATCH',async()=>{
  vi.useFakeTimers()
  const update=vi.spyOn(api,'update').mockRejectedValueOnce(new ApiError('Conflict',409,note('A','remote',2))).mockRejectedValueOnce(new ApiError('Offline',0))
  const onError=vi.fn()
  const {result}=renderHook(()=>useNoteDrafts(async()=>{},onError,true))
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','old')),{body:'local'})))
  await tick()
  expect(result.current.drafts.A).toMatchObject({status:'conflict',body:'local',current:{body:'remote'}})
  act(()=>result.current.setDraft(editDraft(beginDraft(note('B','old')),{body:'local B'})))
  await tick()
  expect(result.current.drafts.B.status).toBe('error')
  await tick(5000)
  expect(update).toHaveBeenCalledTimes(2)
  expect(onError).not.toHaveBeenCalled()
  expect(result.current.drafts.B.errorMessage).toContain('Offline')
 })
 it('allows a manual save after an autosave failure',async()=>{
  vi.useFakeTimers()
  const update=vi.spyOn(api,'update').mockRejectedValueOnce(new ApiError('Offline',0)).mockResolvedValueOnce({item:note('A','local',2)})
  const {result}=renderHook(()=>useNoteDrafts(async()=>{},vi.fn(),true))
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','old')),{body:'local'})))
  await tick()
  expect(result.current.drafts.A.status).toBe('error')
  await act(async()=>{await result.current.save(result.current.drafts.A)})
  expect(update).toHaveBeenNthCalledWith(2,'notes','A',{title:'A',body:'local',project_id:'',version:1})
  expect(result.current.drafts.A).toMatchObject({status:'saved',version:2})
 })
 it('invalidates old completion and timers after discard, logout, and unmount',async()=>{
  vi.useFakeTimers()
  const pending=deferred<{item:Note}>()
  const update=vi.spyOn(api,'update').mockImplementationOnce(()=>pending.promise)
  const reload=vi.fn(async()=>{}),onError=vi.fn()
  const {result,rerender,unmount}=renderHook(({enabled})=>useNoteDrafts(reload,onError,enabled),{initialProps:{enabled:true}})
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','old')),{body:'first'})))
  await tick()
  act(()=>result.current.setDraft(editDraft(result.current.drafts.A,{body:'second'})))
  act(()=>result.current.discard('A'))
  await tick()
  expect(result.current.drafts.A).toBeUndefined()
  act(()=>result.current.setDraft(editDraft(beginDraft(note('B','old')),{body:'pending'})))
  rerender({enabled:false})
  await tick(5000)
  expect(update).toHaveBeenCalledTimes(1)
  expect(result.current.drafts).toEqual({})
  unmount()
  await act(async()=>{pending.resolve({item:note('A','first',2)});await pending.promise})
  expect(update).toHaveBeenCalledTimes(1)
  expect(reload).not.toHaveBeenCalled()
  expect(onError).not.toHaveBeenCalled()
 })
 it('ignores the old response after discard without resurrecting or reloading the note',async()=>{
  vi.useFakeTimers()
  const pending=deferred<{item:Note}>(),reload=vi.fn(async()=>{})
  const update=vi.spyOn(api,'update').mockImplementationOnce(()=>pending.promise)
  const {result}=renderHook(()=>useNoteDrafts(reload,vi.fn(),true))
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','old')),{body:'first'})))
  await tick()
  act(()=>result.current.discard('A'))
  await act(async()=>{pending.resolve({item:note('A','first',2)});await pending.promise})
  await tick(5000)
  expect(result.current.drafts.A).toBeUndefined()
  expect(update).toHaveBeenCalledTimes(1)
  expect(reload).not.toHaveBeenCalled()
 })
 it('ignores completion from a prior enabled generation after reactivation',async()=>{
  vi.useFakeTimers()
  const old=deferred<{item:Note}>(),fresh=deferred<{item:Note}>(),reload=vi.fn(async()=>{})
  const update=vi.spyOn(api,'update').mockImplementationOnce(()=>old.promise).mockImplementationOnce(()=>fresh.promise)
  const {result,rerender}=renderHook(({enabled})=>useNoteDrafts(reload,vi.fn(),enabled),{initialProps:{enabled:true}})
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','old')),{body:'first'})))
  await tick()
  rerender({enabled:false})
  rerender({enabled:true})
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','old')),{body:'new session'})))
  await tick()
  expect(update).toHaveBeenCalledTimes(2)
  await act(async()=>{old.resolve({item:note('A','first',2)});await old.promise})
  expect(reload).not.toHaveBeenCalled()
  expect(result.current.drafts.A.body).toBe('new session')
  await act(async()=>{fresh.resolve({item:note('A','new session',2)});await fresh.promise})
  expect(result.current.drafts.A).toMatchObject({body:'new session',version:2,status:'saved'})
  expect(reload).toHaveBeenCalledTimes(1)
 })
 it('does not process an outstanding response after unmount',async()=>{
  vi.useFakeTimers()
  const pending=deferred<{item:Note}>(),reload=vi.fn(async()=>{}),onError=vi.fn()
  vi.spyOn(api,'update').mockImplementationOnce(()=>pending.promise)
  const {result,unmount}=renderHook(()=>useNoteDrafts(reload,onError,true))
  act(()=>result.current.setDraft(editDraft(beginDraft(note('A','old')),{body:'first'})))
  await tick()
  unmount()
  await act(async()=>{pending.resolve({item:note('A','first',2)});await pending.promise})
  expect(reload).not.toHaveBeenCalled()
  expect(onError).not.toHaveBeenCalled()
 })
})
