import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,expect,it,vi} from 'vitest'
import {api,ApiError} from '../lib/api'
import type {GitHubIssue,GitHubRepository} from '../lib/state'
import {GitHubIssuesView} from './GitHubIssuesView'

afterEach(()=>{cleanup();vi.restoreAllMocks()})

const repositories:GitHubRepository[]=[
 {space_id:'space-a',space_name:'Space A',repository:'acme/a'},
 {space_id:'space-b',space_name:'Space B',repository:'acme/b'},
]
const issue=(number:number,title:string):GitHubIssue=>({number,title,body:'Description',state:'open',url:`https://github.com/acme/a/issues/${number}`,updated_at:'2026-10-06T10:00:00Z'})

it('ignores an old response when the repository changes during loading',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:repositories})
 let resolveA!:(value:{items:GitHubIssue[];page:number;has_more:boolean})=>void
 const oldResponse=new Promise<{items:GitHubIssue[];page:number;has_more:boolean}>(resolve=>{resolveA=resolve})
 vi.spyOn(api,'githubIssues').mockImplementation(spaceId=>spaceId==='space-a'?oldResponse:Promise.resolve({items:[issue(2,'Issue from Space B')],page:1,has_more:false}))
 render(<GitHubIssuesView/>)
 const select=await screen.findByRole('combobox',{name:'Repository'})
 fireEvent.change(select,{target:{value:'space-b'}})
 expect(await screen.findByText('Issue from Space B')).toBeTruthy()
 await act(async()=>{resolveA({items:[issue(1,'Old issue from Space A')],page:1,has_more:false})})
 expect(screen.queryByText('Old issue from Space A')).toBeNull()
 expect(api.githubIssues).toHaveBeenCalledWith('space-b','open',1)
 const link=screen.getByRole('link',{name:'Open issue #2 on GitHub'})
 expect(link.getAttribute('href')).toBe('https://github.com/acme/a/issues/2')
 expect(link.getAttribute('rel')).toBe('noopener noreferrer')
})

it('does not apply an old issue mutation failure to a newly selected repository',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:repositories})
 vi.spyOn(api,'githubIssues').mockImplementation(async spaceId=>({items:[spaceId==='space-a'?issue(1,'Issue A'):issue(2,'Issue B')],page:1,has_more:false}))
 let rejectOld!:(error:Error)=>void,rejectNew!:(error:Error)=>void
 const old=new Promise<{item:GitHubIssue}>((_resolve,reject)=>{rejectOld=reject})
 const next=new Promise<{item:GitHubIssue}>((_resolve,reject)=>{rejectNew=reject})
 vi.spyOn(api,'updateGithubIssue').mockReturnValueOnce(old).mockReturnValueOnce(next)
 render(<GitHubIssuesView/>)
 fireEvent.click(await screen.findByRole('button',{name:'Close issue #1'}))
 fireEvent.change(screen.getByRole('combobox',{name:'Repository'}),{target:{value:'space-b'}})
 expect(await screen.findByText('Issue B')).toBeTruthy()
 fireEvent.click(screen.getByRole('button',{name:'Close issue #2'}))
 expect((screen.getByRole('button',{name:'Close issue #2'}) as HTMLButtonElement).disabled).toBe(true)
 await act(async()=>rejectOld(new ApiError('internal error',500)))
 expect(screen.queryByRole('alert')).toBeNull()
 expect((screen.getByRole('button',{name:'Close issue #2'}) as HTMLButtonElement).disabled).toBe(true)
 expect(screen.getByText('Issue B')).toBeTruthy()
 await act(async()=>rejectNew(new ApiError('internal error',500)))
 expect(screen.getByRole('alert').textContent).toMatch(/Could not confirm/)
})

it('preserves title and body when the remote update fails',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 vi.spyOn(api,'githubIssues').mockResolvedValue({items:[issue(1,'Title original')],page:1,has_more:false})
 vi.spyOn(api,'updateGithubIssue').mockRejectedValue(new Error('Could not update the issue.'))
 render(<GitHubIssuesView/>)
 fireEvent.click(await screen.findByRole('button',{name:'Title original'}))
 const title=screen.getByRole('textbox',{name:'Title'})
 const body=screen.getByRole('textbox',{name:'Description'})
 fireEvent.change(title,{target:{value:'Edited title'}})
 fireEvent.change(body,{target:{value:'Revised body'}})
 fireEvent.click(screen.getByRole('button',{name:'Save changes'}))
 expect((await screen.findByRole('alert')).textContent).toContain('Could not save the issue.')
 expect((screen.getByRole('textbox',{name:'Title'}) as HTMLInputElement).value).toBe('Edited title')
 expect((screen.getByRole('textbox',{name:'Description'}) as HTMLTextAreaElement).value).toBe('Revised body')
 expect(screen.getByRole('heading',{name:'Edit issue #1'})).toBeTruthy()
 expect(api.updateGithubIssue).toHaveBeenCalledWith(1,{space_id:'space-a',title:'Edited title',body:'Revised body'})
})

it('closes an issue with only the Space and new state',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 vi.spyOn(api,'githubIssues').mockResolvedValue({items:[issue(1,'Issue open')],page:1,has_more:false})
 const update=vi.spyOn(api,'updateGithubIssue').mockResolvedValue({item:{...issue(1,'Issue open'),state:'closed'}})
 render(<GitHubIssuesView/>)
 fireEvent.click(await screen.findByRole('button',{name:'Close issue #1'}))
 await waitFor(()=>expect(update).toHaveBeenCalledWith(1,{space_id:'space-a',state:'closed'}))
})

it('submits creation only once while the write is pending',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 vi.spyOn(api,'githubIssues').mockResolvedValue({items:[],page:1,has_more:false})
 let resolveCreate!:(value:{item:GitHubIssue})=>void
 const pending=new Promise<{item:GitHubIssue}>(resolve=>{resolveCreate=resolve})
 const create=vi.spyOn(api,'createGithubIssue').mockReturnValue(pending)
 render(<GitHubIssuesView/>)
 fireEvent.click(await screen.findByRole('button',{name:'Create issue'}))
 fireEvent.change(screen.getByRole('textbox',{name:'Title'}),{target:{value:'New issue'}})
 fireEvent.change(screen.getByRole('textbox',{name:'Description'}),{target:{value:'Detalhes'}})
 const submit=screen.getByRole('button',{name:'Create issue'})
 fireEvent.click(submit)
 fireEvent.click(submit)
 await waitFor(()=>expect(create).toHaveBeenCalledTimes(1))
 expect((screen.getByRole('textbox',{name:'Title'}) as HTMLInputElement).disabled).toBe(true)
 expect((screen.getByRole('textbox',{name:'Description'}) as HTMLTextAreaElement).disabled).toBe(true)
 expect(create).toHaveBeenCalledWith('space-a','New issue','Detalhes')
 await act(async()=>{resolveCreate({item:issue(3,'New issue')})})
})

it('rejects an overlong accented title and preserves the trimmed boundary text',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 vi.spyOn(api,'githubIssues').mockResolvedValue({items:[],page:1,has_more:false})
 const create=vi.spyOn(api,'createGithubIssue').mockResolvedValue({item:issue(4,'Issue with accents')})
 render(<GitHubIssuesView/>)
 fireEvent.click(await screen.findByRole('button',{name:'Create issue'}))
 const title=screen.getByRole('textbox',{name:'Title'})
 const body=screen.getByRole('textbox',{name:'Description'})
 const tooLongTitle='á'.repeat(129)
 const boundaryBody='a'.repeat(65536)
 fireEvent.change(title,{target:{value:tooLongTitle}})
 fireEvent.change(body,{target:{value:boundaryBody}})
 fireEvent.submit(title.closest('form')!)
 expect(create.mock.calls.length).toBe(0)
 expect(title.getAttribute('maxLength')).toBeNull()
 expect(body.getAttribute('maxLength')).toBeNull()
 expect((title as HTMLInputElement).value).toBe(tooLongTitle)
 expect((body as HTMLTextAreaElement).value).toBe(boundaryBody)
 expect(title.getAttribute('aria-invalid')).toBe('true')
 expect(body.getAttribute('aria-invalid')).toBeNull()
 expect((screen.getByRole('button',{name:'Create issue'}) as HTMLButtonElement).disabled).toBe(true)
 expect(screen.getByText(/258 \/ 256 bytes UTF-8/)).toBeTruthy()
 expect(screen.getByText(/65536 \/ 65536 bytes UTF-8/)).toBeTruthy()

 const normalizedTitle='á'.repeat(128)
 const titleWithWhitespace=`  ${normalizedTitle}  `
 fireEvent.change(title,{target:{value:titleWithWhitespace}})
 expect((title as HTMLInputElement).value).toBe(titleWithWhitespace)
 expect(title.getAttribute('aria-invalid')).toBeNull()
 expect(screen.getByText(/256 \/ 256 bytes UTF-8/)).toBeTruthy()
 fireEvent.click(screen.getByRole('button',{name:'Create issue'}))
 await waitFor(()=>expect(create.mock.calls.length).toBe(1))
 expect(create.mock.calls[0]).toEqual(['space-a',normalizedTitle,boundaryBody])
})

it('rejects an overlong body while editing with a valid ASCII title and allows emoji at the boundary',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 vi.spyOn(api,'githubIssues').mockResolvedValue({items:[issue(5,'Issue to edit')],page:1,has_more:false})
 const update=vi.spyOn(api,'updateGithubIssue').mockResolvedValue({item:issue(5,'Issue to edit')})
 render(<GitHubIssuesView/>)
 fireEvent.click(await screen.findByRole('button',{name:'Issue to edit'}))
 const title=screen.getByRole('textbox',{name:'Title'})
 const body=screen.getByRole('textbox',{name:'Description'})
 const boundaryTitle='a'.repeat(256)
 const tooLongBody='a'.repeat(65535)+'é'
 fireEvent.change(title,{target:{value:boundaryTitle}})
 fireEvent.change(body,{target:{value:tooLongBody}})
 fireEvent.submit(title.closest('form')!)
 expect(update.mock.calls.length).toBe(0)
 expect(title.getAttribute('maxLength')).toBeNull()
 expect(body.getAttribute('maxLength')).toBeNull()
 expect((title as HTMLInputElement).value).toBe(boundaryTitle)
 expect((body as HTMLTextAreaElement).value).toBe(tooLongBody)
 expect(title.getAttribute('aria-invalid')).toBeNull()
 expect(body.getAttribute('aria-invalid')).toBe('true')
 expect((screen.getByRole('button',{name:'Save changes'}) as HTMLButtonElement).disabled).toBe(true)
 expect(screen.getByText(/256 \/ 256 bytes UTF-8/)).toBeTruthy()
 expect(screen.getByText(/65537 \/ 65536 bytes UTF-8/)).toBeTruthy()

 const boundaryBody=`  ${'a'.repeat(65530)}😀`
 fireEvent.change(body,{target:{value:boundaryBody}})
 expect(body.getAttribute('aria-invalid')).toBeNull()
 fireEvent.click(screen.getByRole('button',{name:'Save changes'}))
 await waitFor(()=>expect(update.mock.calls.length).toBe(1))
 expect(update.mock.calls[0]).toEqual([5,{space_id:'space-a',title:boundaryTitle,body:boundaryBody}])
})

it('keeps a failed creation draft and asks for a list refresh before retrying',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 vi.spyOn(api,'githubIssues').mockResolvedValue({items:[],page:1,has_more:false})
 vi.spyOn(api,'createGithubIssue').mockRejectedValue(new Error('Connection failed.'))
 render(<GitHubIssuesView/>)
 fireEvent.click(await screen.findByRole('button',{name:'Create issue'}))
 fireEvent.change(screen.getByRole('textbox',{name:'Title'}),{target:{value:'Draft de issue'}})
 fireEvent.change(screen.getByRole('textbox',{name:'Description'}),{target:{value:'Body that should remain'}})
 fireEvent.click(screen.getByRole('button',{name:'Create issue'}))
 expect((await screen.findByRole('alert')).textContent).toContain('refresh the list before trying again')
 expect((screen.getByRole('textbox',{name:'Title'}) as HTMLInputElement).value).toBe('Draft de issue')
 expect((screen.getByRole('textbox',{name:'Description'}) as HTMLTextAreaElement).value).toBe('Body that should remain')
 fireEvent.click(screen.getByRole('button',{name:'Refresh list'}))
 expect((screen.getByRole('textbox',{name:'Title'}) as HTMLInputElement).value).toBe('Draft de issue')
})

it('refreshes the issue list before retrying an uncertain create and omits that warning for a definite 400',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 const list=vi.spyOn(api,'githubIssues').mockResolvedValue({items:[],page:1,has_more:false})
 const create=vi.spyOn(api,'createGithubIssue').mockRejectedValueOnce(new ApiError('internal error',503)).mockResolvedValueOnce({item:issue(8,'New issue')})
 render(<GitHubIssuesView/>)
 fireEvent.click(await screen.findByRole('button',{name:'Create issue'}))
 fireEvent.change(screen.getByRole('textbox',{name:'Title'}),{target:{value:'New issue'}})
 fireEvent.click(screen.getByRole('button',{name:'Create issue'}))
 expect((await screen.findByRole('alert')).textContent).toContain('The issue may have been created')
 const prior=list.mock.calls.length
 fireEvent.click(screen.getByRole('button',{name:'Refresh before retrying'}))
 await screen.findByRole('region',{name:'Updated issues'})
 expect(create).toHaveBeenCalledTimes(1)
 fireEvent.click(screen.getByRole('button',{name:'Create anyway'}))
 await waitFor(()=>expect(create).toHaveBeenCalledTimes(2))
 expect(list.mock.calls.length).toBeGreaterThan(prior)
 expect(list.mock.invocationCallOrder[prior]).toBeLessThan(create.mock.invocationCallOrder[1])
 cleanup();vi.restoreAllMocks()
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 vi.spyOn(api,'githubIssues').mockResolvedValue({items:[],page:1,has_more:false})
 vi.spyOn(api,'createGithubIssue').mockRejectedValue(new ApiError('invalid request',400))
 render(<GitHubIssuesView/>)
 fireEvent.click(await screen.findByRole('button',{name:'Create issue'}))
 fireEvent.change(screen.getByRole('textbox',{name:'Title'}),{target:{value:'New issue'}})
 fireEvent.click(screen.getByRole('button',{name:'Create issue'}))
 expect((await screen.findByRole('alert')).textContent).not.toContain('The issue may have been created')
})

it('shows a remotely created issue after a lost create response before allowing another POST',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 const created=issue(42,'New issue')
 const list=vi.spyOn(api,'githubIssues').mockResolvedValueOnce({items:[],page:1,has_more:false}).mockResolvedValue({items:[created],page:1,has_more:false})
 const create=vi.spyOn(api,'createGithubIssue').mockRejectedValueOnce(new ApiError('internal error',503))
 render(<GitHubIssuesView/>)
 fireEvent.click(await screen.findByRole('button',{name:'Create issue'}))
 fireEvent.change(screen.getByRole('textbox',{name:'Title'}),{target:{value:'New issue'}})
 fireEvent.click(screen.getByRole('button',{name:'Create issue'}))
 expect((await screen.findByRole('alert')).textContent).toContain('The issue may have been created')
 fireEvent.click(screen.getByRole('button',{name:'Refresh before retrying'}))
 expect(await screen.findByText(/#42.*New issue/)).toBeTruthy()
 expect(create).toHaveBeenCalledTimes(1)
 expect(list).toHaveBeenCalledWith('space-a','all',1)
 fireEvent.click(screen.getByRole('button',{name:'Return to list without creating'}))
 await waitFor(()=>expect(screen.queryByRole('heading',{name:'New issue'})).toBeNull())
 expect(create).toHaveBeenCalledTimes(1)
})

it('filters GitHub issues and requests later pages explicitly',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 const list=vi.spyOn(api,'githubIssues').mockImplementation(async(_spaceId,state,page)=>({items:[{...issue(page,`Issue ${state} ${page}`),state:state==='closed'?'closed':'open'}],page,has_more:page<2}))
 render(<GitHubIssuesView/>)
 await screen.findByRole('button',{name:'Issue open 1'})
 fireEvent.click(screen.getByRole('button',{name:'Closed'}))
 await screen.findByRole('button',{name:'Issue closed 1'})
 fireEvent.click(screen.getByRole('button',{name:/Next/}))
 expect(await screen.findByRole('button',{name:'Issue closed 2'})).toBeTruthy()
 expect(list).toHaveBeenCalledWith('space-a','closed',2)
})

it('refreshes repository discovery and issues on demand',async()=>{
 const status=vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 const list=vi.spyOn(api,'githubIssues').mockResolvedValueOnce({items:[issue(1,'Issue anterior')],page:1,has_more:false}).mockResolvedValue({items:[issue(1,'Updated issue')],page:1,has_more:false})
 render(<GitHubIssuesView/>)
 await screen.findByRole('button',{name:'Issue anterior'})
 fireEvent.click(screen.getByRole('button',{name:'Refresh'}))
 expect(await screen.findByRole('button',{name:'Updated issue'})).toBeTruthy()
 expect(status).toHaveBeenCalledTimes(2)
 expect(list.mock.calls.length).toBeGreaterThanOrEqual(2)
})

it('keeps next-page navigation available when the current page has no issues',async()=>{
 const list=vi.spyOn(api,'githubIssues').mockImplementation(async(_spaceId,_state,page)=>page===1?{items:[],page,has_more:true}:{items:[issue(51,'Issue on the next page')],page,has_more:false})
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 render(<GitHubIssuesView/>)
 expect(await screen.findByRole('heading',{name:'No issues on this page'})).toBeTruthy()
 const next=screen.getByRole('button',{name:/Next/}) as HTMLButtonElement
 expect(next.disabled).toBe(false)
 fireEvent.click(next)
 expect(await screen.findByRole('button',{name:'Issue on the next page'})).toBeTruthy()
 expect(list).toHaveBeenCalledWith('space-a','open',2)
})

it('explains when the agent has not authenticated GitHub yet',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:false,message:'gh auth login pending'})
 const repositoriesRequest=vi.spyOn(api,'githubRepositories')
 render(<GitHubIssuesView/>)
 expect((await screen.findByRole('status')).textContent).toContain('GitHub CLI is not authenticated in this environment.')
 expect(repositoriesRequest).not.toHaveBeenCalled()
})

it('allows discovery to be retried after gh authenticates in the terminal',async()=>{
 const status=vi.spyOn(api,'githubStatus').mockResolvedValueOnce({available:true,authenticated:false}).mockResolvedValueOnce({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[repositories[0]]})
 vi.spyOn(api,'githubIssues').mockResolvedValue({items:[],page:1,has_more:false})
 render(<GitHubIssuesView/>)
 fireEvent.click(await screen.findByRole('button',{name:'Check again'}))
 expect(await screen.findByRole('combobox',{name:'Repository'})).toBeTruthy()
 expect(status).toHaveBeenCalledTimes(2)
})

it('shows unavailable and empty repository states without attempting issue reads',async()=>{
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:false,authenticated:false,message:'gh unavailable'})
 const listRepositories=vi.spyOn(api,'githubRepositories')
 const listIssues=vi.spyOn(api,'githubIssues')
 render(<GitHubIssuesView/>)
 expect((await screen.findByRole('status')).textContent).toContain('gh unavailable')
 expect(listRepositories).not.toHaveBeenCalled()
 expect(listIssues).not.toHaveBeenCalled()
 cleanup()
 vi.restoreAllMocks()
 vi.spyOn(api,'githubStatus').mockResolvedValue({available:true,authenticated:true})
 vi.spyOn(api,'githubRepositories').mockResolvedValue({items:[]})
 const emptyIssueList=vi.spyOn(api,'githubIssues')
 render(<GitHubIssuesView/>)
 expect(await screen.findByRole('heading',{name:'No linked repository'})).toBeTruthy()
 expect(emptyIssueList).not.toHaveBeenCalled()
})
