import {useEffect,useRef,useState,type FormEvent} from 'react'
import QRCode from 'qrcode'
import {ArrowRight,Copy,KeyRound,LockKeyhole,RefreshCw,ShieldCheck} from 'lucide-react'
import {Button} from '../components/ui/button'
import {Input} from '../components/ui/input'
import {Brand} from '../components/Brand'
import {api,ApiError} from '../lib/api'
import {apiErrorMessage} from '../lib/apiErrorMessage'
type Pending={secret:string;otpauth_url:string;csrf_token:string}
export function SetupView({available,browserEnabled=false,onReady,onCheckAccess}:{available:boolean;browserEnabled?:boolean;onReady:()=>void;onCheckAccess?:()=>Promise<'available'|'configured'|'denied'>}){
 const [stage,setStage]=useState<'credentials'|'totp'|'recovery'>('credentials')
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[pending,setPending]=useState<Pending|null>(null),[otp,setOtp]=useState(''),[codes,setCodes]=useState<string[]>([]),[ack,setAck]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState('')
 const [checking,setChecking]=useState(false),[accessError,setAccessError]=useState('')
 const canvas=useRef<HTMLCanvasElement>(null)
 useEffect(()=>{if(stage==='totp'&&pending&&canvas.current){QRCode.toCanvas(canvas.current,pending.otpauth_url,{width:188,margin:1,color:{dark:'#18181b',light:'#ffffff'}}).catch(()=>setError('Could not render the QR code. Use the manual key below.'))}},[stage,pending])
 const begin=async(e:FormEvent)=>{e.preventDefault();setError('');if(password!==confirm){setError('Passwords do not match.');return}if(password.length<16){setError('Use a password of at least 16 characters.');return}setBusy(true);try{const result=await api.setupBegin(username.trim(),password);setPassword('');setConfirm('');setPending(result);setStage('totp')}catch(e){setError(e instanceof ApiError&&[401,403].includes(e.status)?'Your authorized access session expired. Sign in through Cloudflare Access and try again.':apiErrorMessage(e,'Could not start setup.'))}finally{setBusy(false)}}
 const complete=async(e:FormEvent)=>{e.preventDefault();if(!pending)return;setBusy(true);setError('');try{const result=await api.setupComplete(otp.trim(),pending.csrf_token);setPending(null);setOtp('');setCodes(result.recovery_codes);setStage('recovery')}catch(e){setOtp('');if(e instanceof ApiError&&e.status===400){setError('Invalid code. Check your authenticator app and try again.')}else if(e instanceof ApiError&&e.status===410){setPending(null);setStage('credentials');setError('Setup expired or exceeded the allowed attempts. Restart to generate a new key.')}else if(e instanceof ApiError&&[401,403].includes(e.status)){setPending(null);setStage('credentials');setError('Your authorized access session expired. Sign in through Cloudflare Access and restart.')}else{setError(apiErrorMessage(e,'Could not verify. Please try again.'))}}finally{setBusy(false)}}
 const copy=async(value:string,what:string)=>{try{await navigator.clipboard.writeText(value);setCopied(what);window.setTimeout(()=>setCopied(''),2500)}catch{setError('Automatic copy failed. Select and copy the text manually.')}}
 const restart=()=>{setPending(null);setOtp('');setPassword('');setConfirm('');setError('');setStage('credentials')}
 const finish=()=>{setPending(null);setPassword('');setConfirm('');setOtp('');setCodes([]);setAck(false);onReady()}
 const checkAccess=async()=>{if(!onCheckAccess)return;setChecking(true);setAccessError('');try{const result=await onCheckAccess();if(result==='denied')setAccessError('Access has not been confirmed. Use Switch Cloudflare Access session and sign in with the owner account.')}catch(e){setAccessError(e instanceof ApiError&&[401,403].includes(e.status)?'Access has not been confirmed. Use Switch Cloudflare Access session and sign in with the owner account.':e instanceof ApiError&&e.status===0?'No connection to the server. Check your connection and try again.':'Could not verify access now. Please try again.')}finally{setChecking(false)}}
 if(!available)return <div className="auth-shell setup-shell"><div className="auth-card setup-card"><Brand/><div className="auth-icon"><LockKeyhole size={26}/></div><h1>{browserEnabled?'Authorized access required':'Set up the owner account'}</h1><p>{browserEnabled?'Sign in through Cloudflare Access as the authorized owner, then check access. You can also create the account on the server with herdr-space auth setup.':'Create the owner account in an interactive terminal on the server with herdr-space auth setup, then refresh this page to sign in.'}</p><div className="setup-access-actions">{browserEnabled?<><Button variant="outline" onClick={checkAccess} disabled={checking}><RefreshCw size={16}/>{checking?'Verifying…':'Check access'}</Button><a href="/cdn-cgi/access/logout">Switch Cloudflare Access session</a></>:<Button variant="outline" onClick={()=>window.location.reload()}><RefreshCw size={16}/>Refresh</Button>}</div>{accessError&&<p className="form-error" role="alert">{accessError}</p>}</div></div>
 return <div className="auth-shell setup-shell"><div className="auth-card setup-card"><Brand/><div className="setup-progress" aria-label="Setup steps"><span className={stage==='credentials'?'active':'done'}>1 <small>Account</small></span><span className={stage==='totp'?'active':stage==='recovery'?'done':''}>2 <small>Authenticator</small></span><span className={stage==='recovery'?'active':''}>3 <small>Recovery</small></span></div>
 {stage==='credentials'&&<><div className="auth-icon"><KeyRound size={25}/></div><h1>Set up your Space</h1><p>Create the owner's credentials. The account will be created only after the authenticator is verified.</p><form onSubmit={begin} className="setup-form"><label className="field"><span>Username</span><Input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required maxLength={64} autoFocus/></label><label className="field"><span>Password</span><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" minLength={16} required/></label><label className="field"><span>Confirm password</span><Input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" minLength={16} required/></label>{error&&<p className="form-error" role="alert">{error}</p>}<Button disabled={busy}>{busy?'Preparing…':'Continue'} <ArrowRight size={16}/></Button></form></>}
 {stage==='totp'&&pending&&<><div className="auth-icon"><ShieldCheck size={25}/></div><h1>Set up authentication</h1><p>Scan the QR code with your authenticator app. Then enter the six-digit code to confirm.</p><div className="setup-qr"><canvas ref={canvas} role="img" aria-label="Authenticator setup QR code" width={188} height={188}/></div><div className="setup-secret"><span>Manual key</span><code>{pending.secret}</code><Button type="button" size="sm" variant="outline" onClick={()=>copy(pending.secret,'secret')}><Copy size={14}/>{copied==='secret'?'Copied':'Copy'}</Button></div><form onSubmit={complete} className="setup-form"><label className="field"><span>Six-digit code</span><Input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required placeholder="000000"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="setup-actions"><Button type="button" variant="ghost" onClick={restart}>Restart</Button><Button disabled={busy||otp.length!==6}>{busy?'Verifying…':'Verify code'}</Button></div></form></>}
 {stage==='recovery'&&<><div className="auth-icon"><ShieldCheck size={25}/></div><h1>Save your recovery codes</h1><p>These one-time codes let you sign in if you lose your authenticator. They appear only now. To sign in, use your password and the next authenticator code, or use one of the recovery codes you saved.</p><div className="recovery-codes" aria-label="Recovery codes">{codes.map(code=><code key={code}>{code}</code>)}</div><Button size="sm" variant="outline" onClick={()=>copy(codes.join('\n'),'codes')}><Copy size={14}/>{copied==='codes'?'Copied':'Copy codes'}</Button>{error&&<p className="form-error" role="alert">{error}</p>}<label className="recovery-ack"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I saved the recovery codes</label><Button className="setup-finish" disabled={!ack} onClick={finish}>Go to sign in <ArrowRight size={16}/></Button></>}
 </div></div>
}
